# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.freesurfer.utils import Decimate
def test_Decimate_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    out_file=dict(name_source='in_file',
    position=-1,
    name_template='%s_dec',
    argstr='%s',
    ),
    args=dict(argstr='%s',
    ),
    terminal_output=dict(mandatory=True,
    nohash=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    min_angle=dict(argstr='-m %g',
    ),
    decimation_level=dict(argstr='-d %g',
    ),
    in_file=dict(position=-2,
    mandatory=True,
    argstr='%s',
    ),
    )
    inputs = Decimate.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_Decimate_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = Decimate.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
